apiVersion: apps/v1
kind: Deployment
metadata:
  name: basic-webserver
  labels:
    app: basic-webserver
spec:
  replicas: 2
  selector:
    matchLabels:
      app: basic-webserver
  template:
    metadata:
      labels:
        app: basic-webserver
    spec:
      containers:
      - name: app
        image: gcr.io/ak-k8s-workshop-h/basic-webserver:{{IMAGE_TAG}}
        ports:
        - name: http
          containerPort: 80
        livenessProbe:
          initialDelaySeconds: 10
          httpGet:
            path: /
            port: 80
        readinessProbe:
          initialDelaySeconds: 10
          httpGet:
            path: /
            port: 80
---
apiVersion: v1
kind: Service
metadata:
  name: basic-webserver
  labels:
    app: basic-webserver
spec:
  type: LoadBalancer
  ports:
  - name: http
    port: 80
    targetPort: 80
    protocol: TCP
  selector:
    app: basic-webserver
