apiVersion: apps/v1
kind: Deployment
metadata:
  name: gitlab-runner
  labels:
    app: gitlab-runner
spec:
  replicas: 1
  selector:
    matchLabels:
      app: gitlab-runner
  template:
    metadata:
      name: gitlab-runner
      labels:
        app: gitlab-runner
    spec:
      containers:
      - args:
        - run
        image: gitlab/gitlab-runner:alpine-v1.9.4
        name: gitlab-runner
        volumeMounts:
        - mountPath: /etc/gitlab-runner
          name: config
        - mountPath: /etc/ssl/certs
          name: cacerts
          readOnly: true
      volumes:
      - configMap:
          name: gitlab-runner
        name: config
      - hostPath:
          path: /etc/ssl/certs
        name: cacerts
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: gitlab-runner
  labels:
    app: gitlab-runner
data:
  config.toml: |-
    concurrent = 1
    check_interval = 0

    [[runners]]
    name = "Kubernetes Runner"
    url = "http://35.197.252.116"
    token = "1ef2f46cf1f8842a4ae60060bcf19d"
    executor = "kubernetes"
    [runners.cache]
    [runners.kubernetes]
        host = ""
        cert_file = ""
        key_file = ""
        ca_file = ""
        image = ""
        namespace = ""
        privileged = true
        cpus = ""
        memory = ""
        service_cpus = ""
        service_memory = ""
        helper_cpus = ""
        helper_memory = ""
        helper_image = ""
